remote_theme: "mmistakes/so-simple-theme@3.2.0"

# Setup
title:               LifeLines
tagline:             'A personal, somewhat poetic blog'
description:         'This personal, somewhat poetic blog by Oliver Freyermuth collects emotions, creative ideas, and uncommon quotes.'
url:                 'https://olifre.github.io'
baseurl:             '/lifelines'
skin:                "/assets/css/skins/dark.css"
logo:                "/images/logo_black.png"
date_format:         "%B %-d, %Y"
read_time:           true
# Poetry is "slower" (default is 200)
words_per_minute:    100
# Disable to reduce unnecessary JS for now
mathjax:             false

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      #comments: true
      share: true
  - scope:
      path: "google*.html"
    values:
      sitemap: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 6
paginate_path: /page:num/

# Search
search_full_content: true

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

author:
  name: Oliver Freyermuth
  email: o.freyermuth@googlemail.com

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

